accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls.resolvers import URLPattern
from . import views

app_name='accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'^signup/$',views.SignUp.as_view(),name='signup'),
]

simplesocial/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls.conf import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name="home"),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(),name='thanks')
]

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):


    def __str__(self):
        return "@{}".format(self.username)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'
        self.fields['username'].label = 'Display Name'

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from . import forms
from django.views.generic import CreateView
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url=reverse_lazy('login')
    template_name = 'accounts/signup.html'

simplesocial/views.py
from django.views.generic import TemplateView


class TestPage(TemplateView):
    template_name='test.html'

class ThanksPage(TemplateView):
    template_name='thanks.html'


class HomePage(TemplateView):
    template_name='index.html'

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Log In</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value="LogIn">

    </form>
</div>


{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value="Sign Up">

    </form>
</div>


{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bikash Social</title>

     <!-- Latest compiled and minified CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
     <!-- Optional theme -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
 
     <!-- Latest compiled and minified JavaScript -->
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

     <link rel="preconnect" href="https://fonts.gstatic.com">
     <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"> 

     <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
</head>
<body>

    <nav class="navbar mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Bikash Social</a>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="#">Post</a></li>
                    <li><a href="#">Groups</a></li>
                    <li><a href="#">Create Group</a></li>
                    <li><a href="{% url 'accounts:logout' %}">LogOut</a></li>
                {% else %}
                    <li><a href="">Groups</a></li>
                    <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}


            </ul>



        </div>



    </nav>
    <div class="container mycontent">
        {% block content %}

    {% endblock content %}
    </div>


    
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to Bikash Site</h1>
{% endblock %}

fas

templates/test.html
{% extends 'base.html' %}

{% block content %}
    <h1>You are now logged in!</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thanks for visiting, come back soon!</h1>
{% endblock %}